stages:
  - build
  - test
  - deploy

build:masskit_ai:
  stage: build
  needs:
    - project: msdc/masskit
      job: build masskit
      ref: main
      artifacts: true
  script:
    - '[ -z "$CI_COMMIT_BRANCH" ] && CONDA_SUFFIX=main || CONDA_SUFFIX=$CI_COMMIT_BRANCH'
    - source $HOME/miniconda3/bin/activate
    - conda activate masskit_ai_cpu_${CONDA_SUFFIX}
    - pip install --force-reinstall masskit-*.whl
    - VERBOSE=1 pip wheel --no-build-isolation .
  tags:
    - linux
    - masskit
  artifacts:
    paths:
      - masskit_ai*.whl

test:masskit_ai:
  stage: test
  needs: 
    - job: "build:masskit_ai"
    - project: msdc/masskit
      job: "build:masskit"
      ref: main
      artifacts: true
  script:
    - '[ -z "$CI_COMMIT_BRANCH" ] && CONDA_SUFFIX=main || CONDA_SUFFIX=$CI_COMMIT_BRANCH'
    - source $HOME/miniconda3/bin/activate
    - conda activate masskit_ai_cpu_${CONDA_SUFFIX}
    - pip install --force-reinstall masskit-*.whl
    - pip install --force-reinstall masskit_ai-*.whl
    - cd tests
    - pytest
    - pip uninstall -y masskit masskit_ai
  tags:
    - linux
    - masskit
